Pet-Clinic-Net6/Models/ErrorViewModel.cs
namespace Pet_Clinic_Net6.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Pet-Clinic-Net6/Controllers/CreditosController.cs
using Microsoft.AspNetCore.Mvc;
using Pet_Clinic_Net6.Models;
using System.Diagnostics;

namespace Pet_Clinic_Net6.Controllers
{
    public class CreditosController : Controller
    {
        private readonly ILogger<CreditosController> _logger;

        public CreditosController(ILogger<CreditosController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Pet-Clinic-Net6/Controllers/DevOpsController.cs
using Microsoft.AspNetCore.Mvc;
using Pet_Clinic_Net6.Models;
using System.Diagnostics;

namespace Pet_Clinic_Net6.Controllers
{
    public class DevOpsController : Controller
    {
        private readonly ILogger<DevOpsController> _logger;

        public DevOpsController(ILogger<DevOpsController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Create()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Pet-Clinic-Net6/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Pet_Clinic_Net6.Models;
using System.Diagnostics;

namespace Pet_Clinic_Net6.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Pet-Clinic-Net6/Views/Creditos/Create.cshtml
@page
@* @model petclinicFront.Pages.Creditos.CreateModel *@

@{
    @* ViewData["Title"] = "Create"; *@
    @* Layout = "~/Pages/Shared/_Layout.cshtml"; *@
}

<h1>Solicitud de Crédito veterinario</h1>

<h4>
    En Contrucción 
</h4>
<hr />
@* <div class="row">
    <div class="col-md-4">

        @if (ViewData["Preautorizado"]?.ToString() == "1" && ViewData["Score"]?.ToString() != null)
        {
            <script type="text/javascript">
                Swal.fire(
                    '¡Felicidades!',
                    'Tu solicitud fué preautorizada, tu score fue: ' + @ViewData["Score"].ToString(),
                    'success'
                );
            </script>
        }
        else if (ViewData["Preautorizado"]?.ToString() != "1" && ViewData["Score"]?.ToString() != null)
        {
            <script type="text/javascript">
                Swal.fire({
                    title: 'Lo sentimos.',
                    text: 'Tu solicitud no fue autorizada, tu score fue: ' + @ViewData["Score"].ToString(),
                    icon: 'error',
                    confirmButtonText: 'Ok'
                });
            </script>
        }




        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Genero: </label>
                <br />
                @Html.RadioButtonFor(model => model.SolicitudCredito.Genero, "false", new { id = "masculino" })
                @Html.Label("masculino", "Masculino")
                @Html.RadioButtonFor(model => model.SolicitudCredito.Genero, "true", new { id = "femenino" })
                @Html.Label("femenino", "Femenino")
                <span asp-validation-for="SolicitudCredito.Genero" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label class="control-label">¿Es casado?</label>
                <input asp-for="SolicitudCredito.EsCasado" class="form-control" />
                <span asp-validation-for="SolicitudCredito.EsCasado" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label class="control-label">¿Cuantas personas dependen de usted?</label>
                <input asp-for="SolicitudCredito.NumeroDependientes" class="form-control" />
                <span asp-validation-for="SolicitudCredito.NumeroDependientes" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label class="control-label">¿Tiene estudios universitarios finalizados?</label>
                <input asp-for="SolicitudCredito.UniversidadFinalizada" class="form-control" />
                <span asp-validation-for="SolicitudCredito.UniversidadFinalizada" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label class="control-label">¿Es económicamente independiente?</label>
                <input asp-for="SolicitudCredito.EsIndependiente" class="form-control" />
                <span asp-validation-for="SolicitudCredito.EsIndependiente" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label class="control-label">¿A cuanto ascienden sus ingresos mensuales directos?</label>
                <input asp-for="SolicitudCredito.IngresosDirectos" class="form-control" />
                <span asp-validation-for="SolicitudCredito.IngresosDirectos" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label class="control-label">¿A cuanto ascienden sus ingresos mensuales indirectos?</label>
                <input asp-for="SolicitudCredito.IngresosIndirectos" class="form-control" />
                <span asp-validation-for="SolicitudCredito.IngresosIndirectos" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label class="control-label">¿Ya tiene historial crediticio?</label>
                <input asp-for="SolicitudCredito.PoseeHistorialCrediticio" class="form-control" />
                <span asp-validation-for="SolicitudCredito.PoseeHistorialCrediticio" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label class="control-label">En que tipo de área está ubicada su vivienda:</label>
                <select asp-for="SolicitudCredito.TipoAreaVivienda" asp-items="Model.LookUpArea" class="form-control"></select>
                <span asp-validation-for="SolicitudCredito.TipoAreaVivienda" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label class="control-label">¿Cuál es el monto que solicita?</label>
                <input asp-for="SolicitudCredito.MontoSolicitado" class="form-control" />
                <span asp-validation-for="SolicitudCredito.MontoSolicitado" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label class="control-label">Elija los plazos para su crédito:</label>
                <select asp-for="SolicitudCredito.TiempoDiasCredito" asp-items="Model.LookUpPlazos" class="form-control"></select>
                <span asp-validation-for="SolicitudCredito.TiempoDiasCredito" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Atrás</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
} *@

Pet-Clinic-Net6/Views/Creditos/Index.cshtml
@page
@* @model petclinicFront.Pages.Creditos.IndexModel *@

@{
    @* ViewData["Title"] = "Index"; *@
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="jumbotron">
    <h1 class="display-4">Solicitud de créditos</h1>
    <p class="lead">En esta sección puedes solicitar tu crédito veterinario, haz click en el botón mas abajo, para llenar un formulario y al instante obtén una preautorización..</p>
    <hr class="my-4">
    <img src="~/images/pets.png" alt="Pets" />
    <p>Con tu crédito puedes atender emergencias con tus Mascotas. ¡Date una oportunidad y dáselas a ellos!</p>
    <a class="btn btn-primary btn-lg" role="button" asp-action="Create">Realizar una solicitud de crédito veterinario</a>
</div>

Pet-Clinic-Net6/Views/DevOps/Create.cshtml
@page
@* @model petclinicFront.Pages.DevOps.IndexModel *@
@{
}
<h1>Nuevo registro de mascota</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" id="form_mascotas">
            <div class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Tipo de mascota</label>
                <select class="form-control" id="tipo_mascota">
                    <option value="">Selecciona</option>
                    <option value="Perro">Perro</option>
                    <option value="Gato">Gato</option>
                    <option value="Ave">Ave</option>
                    <option value="Reptil">Reptil</option>
                </select>
                <span class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Nombre de la mascota</label>
                <input class="form-control" id="nombre_mascota" />
                <span class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Peso</label>
                <input class="form-control" id="peso" />
                <span class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Color</label>
                <input class="form-control" id="color" />
                <span class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" id="submit" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
<script>
    // A $( document ).ready() block.
    $(document).ready(function () {
        $("#submit").click((event) => {
            event.preventDefault();
            let tipo = $("#tipo_mascota")
            let nombre = $("#nombre_mascota")
            let peso = $("#peso")
            let color = $("#color")

            vTipo = validarCampo(tipo)
            vNombre = validarCampo(nombre)
            vPeso = validarCampo(peso)
            vColor = validarCampo(color)

            if (vTipo == true && vNombre == true && vPeso == true && vColor == true) {

                let data2Save = {
                    "tipo": tipo.val(),
                    "nombre": nombre.val(),
                    "peso": peso.val(),
                    "color": color.val()
                }

                let mascotas = localStorage.getItem('mascotas')
                mascotas = mascotas == null ? [] : JSON.parse(mascotas)
                mascotas.push(data2Save)

                localStorage.setItem('mascotas', JSON.stringify(mascotas))

                alert("El registro ha sido guardado exitosamente")

                $("#form_mascotas")[0].reset()
            }
        })

        function validarCampo(elemento) {
            elemento.val() == "" ? elemento.next().html("Campo requerido") : elemento.next().html("")
            return elemento.val() == "" ? false : true
        }
    })
</script>

Pet-Clinic-Net6/Views/DevOps/Index.cshtml
@page
@* @model petclinicFront.Pages.DevOps.IndexModel *@
@{
}
<h1>Lista Mascotas</h1>

<div>
    <a asp-action="Create">Agregar mascota desde taller parte 3</a>
</div>
<hr />
<div class="row">
    <div class="col-md-12">
        <table class="table" id="tabla_mascotas">
            <thead>
                <tr>
                    <th scope="col">Tipo</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Peso</th>
                    <th scope="col">Color</th>
                </tr>
            </thead>
            <tbody>

            </tbody>
        </table>
    </div>
</div>

<script>
    // A $( document ).ready() block.
    $(document).ready(function () {
        let mascotas = localStorage.getItem('mascotas')
        let html = ''
        mascotas = mascotas == null ? [] : JSON.parse(mascotas)

        $.each(mascotas, (i, v) => {
            html+= `
                <tr>
                    <td>${v.tipo}</th>
                    <td>${v.nombre}</td>
                    <td>${v.peso}</td>
                    <td>${v.color}</td>
                </tr>`
        })

        $("#tabla_mascotas").find("tbody").html(html)
    })
</script>

Pet-Clinic-Net6/Views/Home/Index.cshtml
@* @page
@model IndexModel *@
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Bienvenido a Petclinic commit</h1>
    <p>Aprender más sobre <a href="https://docs.microsoft.com/aspnet/core">Construir sitios web con ASP.NET CORE</a>.</p>
    <img src="~/images/pets.png" alt="Pets" />
</div>

Pet-Clinic-Net6/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PetClinic</title>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-default navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="Home"  asp-action="Index">PetClinic test</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav navbar-right flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-action="Index">Home</a>
                        </li>
                     @*    <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-action="/Duenos/Index">Clientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-action="/Veterinarios/Index">Veterinarios</a>
                        </li> *@
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Creditos" asp-action="Index">Solicitar Mi crédito veterinario</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="DevOps" asp-action="Index">Registro de Mascota</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - PetClinic - <a asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>